# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebf96026a8a360e5467eee67faa6f359a36120aa418422b222ac8c46421b7a71e4c76ca6f3bcb0c21bc7be61c1cbf8c51e665009751e1396022397d69fdf5a14

test:
  secret_key_base: 853908178ff23febc88bb8b24dff2b329e1db9a93db1854e5badfd527ebfbe52f58862c7202ffd02ebe047066c8fd0c84623fffc088b63346b7170001ffc2c23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
